# Generated by Django 4.1.4 on 2023-01-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Producto', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('Descripcion', models.TextField(max_length=200, unique=True)),
                ('Precio', models.IntegerField()),
                ('Imagen', models.ImageField(upload_to='photos/productos')),
                ('stock', models.IntegerField()),
                ('Activo', models.BooleanField(default=True)),
                ('Fecha_Creacion', models.DateField(auto_now_add=True)),
                ('Fecha_Modificacion', models.DateField(auto_now=True)),
            ],
        ),
    ]
